 # x-axis: red, y-axis: green, z-axis:blue


/tracking/verbose 0
/event/verbose 0
/control/verbose 0
/material/verbose 0
/process/em/verbose 0
/process/list
/process/eLoss/StepFunction 0.1 0.001 um

# Default primary input file (used when no command-line override is provided)
/powtex/source/inputFile data/input/VitessDataPOWTEX/noutascii_biosample_r.dat
#/powtex/source/inputFile data/input/VitessDataPOWTEX/isotrop_reduced.dat

/run/beamOn 1